;==================================================
; Rule Set
;==================================================
ruleset=🏠 国内直连,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/CompanyDirect.list
ruleset=🏢 公司内网,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Company.list
ruleset=🏠 国内直连,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Direct.list

ruleset=🤖 AI服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/AI.list
ruleset=🤖 AI服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/MetaAi.list
ruleset=🤖 AI服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Perplexity.list

ruleset=📺 流媒体,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/TikTok.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Telegram.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Twitter.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Youtube.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Disney.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Netflix.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/HBO.list
ruleset=📺 流媒体,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Spotify.list

ruleset=🎮 游戏服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Steam.list
ruleset=🎮 游戏服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Epic.list
ruleset=🎮 游戏服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/EA.list
ruleset=🎮 游戏服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Blizzard.list
ruleset=🎮 游戏服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/UBI.list
ruleset=🎮 游戏服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Sony.list
ruleset=🎮 游戏服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Nintendo.list

ruleset=💻 开发环境,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/GitHub.list
ruleset=💻 开发环境,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/DevEnv.list

ruleset=✈️ 国际服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Amazon.list
ruleset=✈️ 国际服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Whatsapp.list
ruleset=✈️ 国际服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Facebook.list
ruleset=✈️ 国际服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Google.list
ruleset=✈️ 国际服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/OKX.list
ruleset=✈️ 国际服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/xnb.list
ruleset=✈️ 国际服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Check.list
ruleset=✈️ 国际服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Proxy.list
ruleset=✈️ 国际服务,https://raw.githubusercontent.com/iamqiqi1017/myClashRule/main/list/Global.list

ruleset=🏠 国内直连,[]GEOSITE,cn

ruleset=✈️ 国际服务,[]FINAL


;==================================================
; Policy Group
;==================================================

custom_proxy_group=🤖 AI服务`select`[]🚀 智能切换`[]⚡ 低延迟`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇹🇼 台湾`[]🇭🇰 香港`[]🇰🇷 韩国`[]🇺🇸 美国`[]🕹️ 手动选择`[]DIRECT`[]REJECT

custom_proxy_group=🏢 公司内网`select`[]DIRECT`(?i)atrust`[]🕹️ 手动选择

custom_proxy_group=📺 流媒体`select`[]🚀 智能切换`[]⚡ 低延迟`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇺🇸 美国`[]🕹️ 手动选择`[]DIRECT`[]REJECT

custom_proxy_group=🎮 游戏服务`select`[]🚀 智能切换`[]⚡ 低延迟`[]🇯🇵 日本`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇺🇸 美国`[]🕹️ 手动选择`[]DIRECT`[]REJECT

custom_proxy_group=💻 开发环境`select`[]🚀 智能切换`[]⚡ 低延迟`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇺🇸 美国`[]🕹️ 手动选择`[]DIRECT`[]REJECT

custom_proxy_group=✈️ 国际服务`select`[]🚀 智能切换`[]⚡ 低延迟`[]🕹️ 手动选择`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇰🇷 韩国`[]🇺🇸 美国`[]DIRECT`[]REJECT

custom_proxy_group=🏠 国内直连`select`[]DIRECT`[]REJECT


;==================================================
; Global Node Pool
;==================================================

custom_proxy_group=🕹️ 手动选择`select`^(?!.*(官网|建议|流量|优惠|测试|test|过期|剩余)).*

custom_proxy_group=🚀 智能切换`fallback`^(?!.*(官网|建议|流量|优惠|测试|test|过期|剩余)).*`https://cp.cloudflare.com/generate_204`300,,50

custom_proxy_group=⚡ 低延迟`url-test`^(?!.*(官网|建议|流量|优惠|测试|test|过期|剩余)).*`https://cp.cloudflare.com/generate_204`300,,50


;==================================================
; Region Groups
;==================================================

custom_proxy_group=🇭🇰 香港`url-test`(广港|香港|HK|Hong Kong|HongKong|🇭🇰)`https://cp.cloudflare.com/generate_204`300,,50

custom_proxy_group=🇹🇼 台湾`url-test`(广台|台湾|台灣|TW|Tai Wan|TaiWan|Taiwan|🇹🇼)`https://cp.cloudflare.com/generate_204`300,,50

custom_proxy_group=🇯🇵 日本`url-test`(广日|日本|JP|东京|大阪|埼玉|川日|泉日|沪日|深日|Japan|🇯🇵)`https://cp.cloudflare.com/generate_204`300,,50

custom_proxy_group=🇸🇬 新加坡`url-test`(广新|新加坡|SG|坡|狮城|Singapore|🇸🇬)`https://cp.cloudflare.com/generate_204`300,,50

custom_proxy_group=🇰🇷 韩国`url-test`(广韩|韩国|韓國|KR|首尔|春川|Korea|🇰🇷)`https://cp.cloudflare.com/generate_204`300,,50

custom_proxy_group=🇺🇸 美国`url-test`(广美|美|US|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|🇺🇸)`https://cp.cloudflare.com/generate_204`300,,50


;==================================================
; Rule Generator
;==================================================

enable_rule_generator=true
overwrite_original_rules=true
